[/Script/ProgressionSystemRuntime.PSWorldSubsystem]
PSDataAssetInternal=/ProgressionSystem/DataAssets/DA_ProgressionSystem.DA_ProgressionSystem

; Increment save file version extennsion to force users run empty save
; Increment whenever a major changes done with safe file structure
SaveFileVersionExtensionInternal=2